### ISSUE TITLE
AZ CLI Feedback

### ISSUE THREAD

**Issue by tekgnu** [autocloudarc/0026-azure-automation-plus-dsc-lab#4]
I just wanted to provide two minor comments on the AZ CLI script.   First I would recommend adding a comment on the last line for the AZ group deployment to be careful on the copy and pasting with multi-line (more of an issues when using WSL), secondly there is a typo in that command line: "studentRadnomInfix=$studentRandomInfix", with the parameter name was typo.

**Comment by autocloudarc** [comment]
Thanks @tekgnu. I've updated the README file now with those suggestions. :-) 👍
